// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class LockIdIntermediaryAccountConnection {
  static encode(
    message: LockIdIntermediaryAccountConnection,
    writer: Writer
  ): void {
    writer.uint32(8);
    writer.uint64(message.lockId);

    writer.uint32(18);
    writer.string(message.intermediaryAccount);
  }

  static decode(
    reader: Reader,
    length: i32
  ): LockIdIntermediaryAccountConnection {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new LockIdIntermediaryAccountConnection();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.lockId = reader.uint64();
          break;

        case 2:
          message.intermediaryAccount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  lockId: u64;
  intermediaryAccount: string;

  constructor(lockId: u64 = 0, intermediaryAccount: string = "") {
    this.lockId = lockId;
    this.intermediaryAccount = intermediaryAccount;
  }
}

export function encodeLockIdIntermediaryAccountConnection(
  message: LockIdIntermediaryAccountConnection
): Uint8Array {
  return Protobuf.encode(message, LockIdIntermediaryAccountConnection.encode);
}

export function decodeLockIdIntermediaryAccountConnection(
  buffer: Uint8Array
): LockIdIntermediaryAccountConnection {
  return Protobuf.decode<LockIdIntermediaryAccountConnection>(
    buffer,
    LockIdIntermediaryAccountConnection.decode
  );
}
