// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Coin } from "../../cosmos/base/v1beta1/Coin";

export class SuperfluidDelegationRecord {
  static encode(message: SuperfluidDelegationRecord, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.delegatorAddress);

    writer.uint32(18);
    writer.string(message.validatorAddress);

    const delegationAmount = message.delegationAmount;
    if (delegationAmount !== null) {
      writer.uint32(26);
      writer.fork();
      Coin.encode(delegationAmount, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): SuperfluidDelegationRecord {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SuperfluidDelegationRecord();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.delegatorAddress = reader.string();
          break;

        case 2:
          message.validatorAddress = reader.string();
          break;

        case 3:
          message.delegationAmount = Coin.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  delegatorAddress: string;
  validatorAddress: string;
  delegationAmount: Coin | null;

  constructor(
    delegatorAddress: string = "",
    validatorAddress: string = "",
    delegationAmount: Coin | null = null
  ) {
    this.delegatorAddress = delegatorAddress;
    this.validatorAddress = validatorAddress;
    this.delegationAmount = delegationAmount;
  }
}

export function encodeSuperfluidDelegationRecord(
  message: SuperfluidDelegationRecord
): Uint8Array {
  return Protobuf.encode(message, SuperfluidDelegationRecord.encode);
}

export function decodeSuperfluidDelegationRecord(
  buffer: Uint8Array
): SuperfluidDelegationRecord {
  return Protobuf.decode<SuperfluidDelegationRecord>(
    buffer,
    SuperfluidDelegationRecord.decode
  );
}
