// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class RequestDeliverTx {
  static encode(message: RequestDeliverTx, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.tx);
  }

  static decode(reader: Reader, length: i32): RequestDeliverTx {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RequestDeliverTx();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.tx = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  tx: Uint8Array;

  constructor(tx: Uint8Array = new Uint8Array(0)) {
    this.tx = tx;
  }
}

export function encodeRequestDeliverTx(message: RequestDeliverTx): Uint8Array {
  return Protobuf.encode(message, RequestDeliverTx.encode);
}

export function decodeRequestDeliverTx(buffer: Uint8Array): RequestDeliverTx {
  return Protobuf.decode<RequestDeliverTx>(buffer, RequestDeliverTx.decode);
}
