// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class RequestListSnapshots {
  static encode(message: RequestListSnapshots, writer: Writer): void {}

  static decode(reader: Reader, length: i32): RequestListSnapshots {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RequestListSnapshots();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeRequestListSnapshots(
  message: RequestListSnapshots
): Uint8Array {
  return Protobuf.encode(message, RequestListSnapshots.encode);
}

export function decodeRequestListSnapshots(
  buffer: Uint8Array
): RequestListSnapshots {
  return Protobuf.decode<RequestListSnapshots>(
    buffer,
    RequestListSnapshots.decode
  );
}
