// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class RequestFlush {
  static encode(message: RequestFlush, writer: Writer): void {}

  static decode(reader: Reader, length: i32): RequestFlush {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RequestFlush();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeRequestFlush(message: RequestFlush): Uint8Array {
  return Protobuf.encode(message, RequestFlush.encode);
}

export function decodeRequestFlush(buffer: Uint8Array): RequestFlush {
  return Protobuf.decode<RequestFlush>(buffer, RequestFlush.decode);
}
