// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class RequestEndBlock {
  static encode(message: RequestEndBlock, writer: Writer): void {
    writer.uint32(8);
    writer.int64(message.height);
  }

  static decode(reader: Reader, length: i32): RequestEndBlock {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RequestEndBlock();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.height = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  height: i64;

  constructor(height: i64 = 0) {
    this.height = height;
  }
}

export function encodeRequestEndBlock(message: RequestEndBlock): Uint8Array {
  return Protobuf.encode(message, RequestEndBlock.encode);
}

export function decodeRequestEndBlock(buffer: Uint8Array): RequestEndBlock {
  return Protobuf.decode<RequestEndBlock>(buffer, RequestEndBlock.decode);
}
