// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { CheckTxType } from "./CheckTxType";

export class RequestCheckTx {
  static encode(message: RequestCheckTx, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.tx);

    writer.uint32(16);
    writer.int32(message.type);
  }

  static decode(reader: Reader, length: i32): RequestCheckTx {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RequestCheckTx();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.tx = reader.bytes();
          break;

        case 2:
          message.type = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  tx: Uint8Array;
  type: CheckTxType;

  constructor(tx: Uint8Array = new Uint8Array(0), type: CheckTxType = 0) {
    this.tx = tx;
    this.type = type;
  }
}

export function encodeRequestCheckTx(message: RequestCheckTx): Uint8Array {
  return Protobuf.encode(message, RequestCheckTx.encode);
}

export function decodeRequestCheckTx(buffer: Uint8Array): RequestCheckTx {
  return Protobuf.decode<RequestCheckTx>(buffer, RequestCheckTx.decode);
}
