// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class RequestCommit {
  static encode(message: RequestCommit, writer: Writer): void {}

  static decode(reader: Reader, length: i32): RequestCommit {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RequestCommit();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeRequestCommit(message: RequestCommit): Uint8Array {
  return Protobuf.encode(message, RequestCommit.encode);
}

export function decodeRequestCommit(buffer: Uint8Array): RequestCommit {
  return Protobuf.decode<RequestCommit>(buffer, RequestCommit.decode);
}
