// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Result } from "./ResponseOfferSnapshot/Result";

@unmanaged
export class ResponseOfferSnapshot {
  static encode(message: ResponseOfferSnapshot, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.result);
  }

  static decode(reader: Reader, length: i32): ResponseOfferSnapshot {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ResponseOfferSnapshot();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.result = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  result: Result;

  constructor(result: Result = 0) {
    this.result = result;
  }
}

export function encodeResponseOfferSnapshot(
  message: ResponseOfferSnapshot
): Uint8Array {
  return Protobuf.encode(message, ResponseOfferSnapshot.encode);
}

export function decodeResponseOfferSnapshot(
  buffer: Uint8Array
): ResponseOfferSnapshot {
  return Protobuf.decode<ResponseOfferSnapshot>(
    buffer,
    ResponseOfferSnapshot.decode
  );
}
