// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class MerklePrefix {
  static encode(message: MerklePrefix, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.keyPrefix);
  }

  static decode(reader: Reader, length: i32): MerklePrefix {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MerklePrefix();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.keyPrefix = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  keyPrefix: Uint8Array;

  constructor(keyPrefix: Uint8Array = new Uint8Array(0)) {
    this.keyPrefix = keyPrefix;
  }
}

export function encodeMerklePrefix(message: MerklePrefix): Uint8Array {
  return Protobuf.encode(message, MerklePrefix.encode);
}

export function decodeMerklePrefix(buffer: Uint8Array): MerklePrefix {
  return Protobuf.decode<MerklePrefix>(buffer, MerklePrefix.decode);
}
