// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Coin } from "../../../../cosmos/base/v1beta1/Coin";
import { Height } from "../../../core/client/v1/Height";

export class MsgTransfer {
  static encode(message: MsgTransfer, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.sourcePort);

    writer.uint32(18);
    writer.string(message.sourceChannel);

    const token = message.token;
    if (token !== null) {
      writer.uint32(26);
      writer.fork();
      Coin.encode(token, writer);
      writer.ldelim();
    }

    writer.uint32(34);
    writer.string(message.sender);

    writer.uint32(42);
    writer.string(message.receiver);

    const timeoutHeight = message.timeoutHeight;
    if (timeoutHeight !== null) {
      writer.uint32(50);
      writer.fork();
      Height.encode(timeoutHeight, writer);
      writer.ldelim();
    }

    writer.uint32(56);
    writer.uint64(message.timeoutTimestamp);
  }

  static decode(reader: Reader, length: i32): MsgTransfer {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgTransfer();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sourcePort = reader.string();
          break;

        case 2:
          message.sourceChannel = reader.string();
          break;

        case 3:
          message.token = Coin.decode(reader, reader.uint32());
          break;

        case 4:
          message.sender = reader.string();
          break;

        case 5:
          message.receiver = reader.string();
          break;

        case 6:
          message.timeoutHeight = Height.decode(reader, reader.uint32());
          break;

        case 7:
          message.timeoutTimestamp = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  sourcePort: string;
  sourceChannel: string;
  token: Coin | null;
  sender: string;
  receiver: string;
  timeoutHeight: Height | null;
  timeoutTimestamp: u64;

  constructor(
    sourcePort: string = "",
    sourceChannel: string = "",
    token: Coin | null = null,
    sender: string = "",
    receiver: string = "",
    timeoutHeight: Height | null = null,
    timeoutTimestamp: u64 = 0
  ) {
    this.sourcePort = sourcePort;
    this.sourceChannel = sourceChannel;
    this.token = token;
    this.sender = sender;
    this.receiver = receiver;
    this.timeoutHeight = timeoutHeight;
    this.timeoutTimestamp = timeoutTimestamp;
  }
}

export function encodeMsgTransfer(message: MsgTransfer): Uint8Array {
  return Protobuf.encode(message, MsgTransfer.encode);
}

export function decodeMsgTransfer(buffer: Uint8Array): MsgTransfer {
  return Protobuf.decode<MsgTransfer>(buffer, MsgTransfer.decode);
}
