// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgTransferResponse {
  static encode(message: MsgTransferResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgTransferResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgTransferResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgTransferResponse(
  message: MsgTransferResponse
): Uint8Array {
  return Protobuf.encode(message, MsgTransferResponse.encode);
}

export function decodeMsgTransferResponse(
  buffer: Uint8Array
): MsgTransferResponse {
  return Protobuf.decode<MsgTransferResponse>(
    buffer,
    MsgTransferResponse.decode
  );
}
