// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class ConfigurationDescriptor {
  static encode(message: ConfigurationDescriptor, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.bech32AccountAddressPrefix);
  }

  static decode(reader: Reader, length: i32): ConfigurationDescriptor {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ConfigurationDescriptor();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.bech32AccountAddressPrefix = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  bech32AccountAddressPrefix: string;

  constructor(bech32AccountAddressPrefix: string = "") {
    this.bech32AccountAddressPrefix = bech32AccountAddressPrefix;
  }
}

export function encodeConfigurationDescriptor(
  message: ConfigurationDescriptor
): Uint8Array {
  return Protobuf.encode(message, ConfigurationDescriptor.encode);
}

export function decodeConfigurationDescriptor(
  buffer: Uint8Array
): ConfigurationDescriptor {
  return Protobuf.decode<ConfigurationDescriptor>(
    buffer,
    ConfigurationDescriptor.decode
  );
}
