// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class GetAuthnDescriptorRequest {
  static encode(message: GetAuthnDescriptorRequest, writer: Writer): void {}

  static decode(reader: Reader, length: i32): GetAuthnDescriptorRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetAuthnDescriptorRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeGetAuthnDescriptorRequest(
  message: GetAuthnDescriptorRequest
): Uint8Array {
  return Protobuf.encode(message, GetAuthnDescriptorRequest.encode);
}

export function decodeGetAuthnDescriptorRequest(
  buffer: Uint8Array
): GetAuthnDescriptorRequest {
  return Protobuf.decode<GetAuthnDescriptorRequest>(
    buffer,
    GetAuthnDescriptorRequest.decode
  );
}
