// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class GetCodecDescriptorRequest {
  static encode(message: GetCodecDescriptorRequest, writer: Writer): void {}

  static decode(reader: Reader, length: i32): GetCodecDescriptorRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetCodecDescriptorRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeGetCodecDescriptorRequest(
  message: GetCodecDescriptorRequest
): Uint8Array {
  return Protobuf.encode(message, GetCodecDescriptorRequest.encode);
}

export function decodeGetCodecDescriptorRequest(
  buffer: Uint8Array
): GetCodecDescriptorRequest {
  return Protobuf.decode<GetCodecDescriptorRequest>(
    buffer,
    GetCodecDescriptorRequest.decode
  );
}
