// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class GetQueryServicesDescriptorRequest {
  static encode(
    message: GetQueryServicesDescriptorRequest,
    writer: Writer
  ): void {}

  static decode(
    reader: Reader,
    length: i32
  ): GetQueryServicesDescriptorRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetQueryServicesDescriptorRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeGetQueryServicesDescriptorRequest(
  message: GetQueryServicesDescriptorRequest
): Uint8Array {
  return Protobuf.encode(message, GetQueryServicesDescriptorRequest.encode);
}

export function decodeGetQueryServicesDescriptorRequest(
  buffer: Uint8Array
): GetQueryServicesDescriptorRequest {
  return Protobuf.decode<GetQueryServicesDescriptorRequest>(
    buffer,
    GetQueryServicesDescriptorRequest.decode
  );
}
