// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { TxDescriptor } from "./TxDescriptor";

export class GetTxDescriptorResponse {
  static encode(message: GetTxDescriptorResponse, writer: Writer): void {
    const tx = message.tx;
    if (tx !== null) {
      writer.uint32(10);
      writer.fork();
      TxDescriptor.encode(tx, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): GetTxDescriptorResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetTxDescriptorResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.tx = TxDescriptor.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  tx: TxDescriptor | null;

  constructor(tx: TxDescriptor | null = null) {
    this.tx = tx;
  }
}

export function encodeGetTxDescriptorResponse(
  message: GetTxDescriptorResponse
): Uint8Array {
  return Protobuf.encode(message, GetTxDescriptorResponse.encode);
}

export function decodeGetTxDescriptorResponse(
  buffer: Uint8Array
): GetTxDescriptorResponse {
  return Protobuf.decode<GetTxDescriptorResponse>(
    buffer,
    GetTxDescriptorResponse.decode
  );
}
