// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class MsgDescriptor {
  static encode(message: MsgDescriptor, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.msgTypeUrl);
  }

  static decode(reader: Reader, length: i32): MsgDescriptor {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgDescriptor();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.msgTypeUrl = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  msgTypeUrl: string;

  constructor(msgTypeUrl: string = "") {
    this.msgTypeUrl = msgTypeUrl;
  }
}

export function encodeMsgDescriptor(message: MsgDescriptor): Uint8Array {
  return Protobuf.encode(message, MsgDescriptor.encode);
}

export function decodeMsgDescriptor(buffer: Uint8Array): MsgDescriptor {
  return Protobuf.decode<MsgDescriptor>(buffer, MsgDescriptor.decode);
}
