// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgFundCommunityPoolResponse {
  static encode(message: MsgFundCommunityPoolResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgFundCommunityPoolResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgFundCommunityPoolResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgFundCommunityPoolResponse(
  message: MsgFundCommunityPoolResponse
): Uint8Array {
  return Protobuf.encode(message, MsgFundCommunityPoolResponse.encode);
}

export function decodeMsgFundCommunityPoolResponse(
  buffer: Uint8Array
): MsgFundCommunityPoolResponse {
  return Protobuf.decode<MsgFundCommunityPoolResponse>(
    buffer,
    MsgFundCommunityPoolResponse.decode
  );
}
