// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgSetWithdrawAddressResponse {
  static encode(message: MsgSetWithdrawAddressResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgSetWithdrawAddressResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgSetWithdrawAddressResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgSetWithdrawAddressResponse(
  message: MsgSetWithdrawAddressResponse
): Uint8Array {
  return Protobuf.encode(message, MsgSetWithdrawAddressResponse.encode);
}

export function decodeMsgSetWithdrawAddressResponse(
  buffer: Uint8Array
): MsgSetWithdrawAddressResponse {
  return Protobuf.decode<MsgSetWithdrawAddressResponse>(
    buffer,
    MsgSetWithdrawAddressResponse.decode
  );
}
