// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class MsgSetWithdrawAddress {
  static encode(message: MsgSetWithdrawAddress, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.delegatorAddress);

    writer.uint32(18);
    writer.string(message.withdrawAddress);
  }

  static decode(reader: Reader, length: i32): MsgSetWithdrawAddress {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgSetWithdrawAddress();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.delegatorAddress = reader.string();
          break;

        case 2:
          message.withdrawAddress = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  delegatorAddress: string;
  withdrawAddress: string;

  constructor(delegatorAddress: string = "", withdrawAddress: string = "") {
    this.delegatorAddress = delegatorAddress;
    this.withdrawAddress = withdrawAddress;
  }
}

export function encodeMsgSetWithdrawAddress(
  message: MsgSetWithdrawAddress
): Uint8Array {
  return Protobuf.encode(message, MsgSetWithdrawAddress.encode);
}

export function decodeMsgSetWithdrawAddress(
  buffer: Uint8Array
): MsgSetWithdrawAddress {
  return Protobuf.decode<MsgSetWithdrawAddress>(
    buffer,
    MsgSetWithdrawAddress.decode
  );
}
