// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Coin } from "../../cosmos/base/v1beta1/Coin";

export class MsgBeginUnlocking {
  static encode(message: MsgBeginUnlocking, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.owner);

    writer.uint32(16);
    writer.uint64(message.iD);

    const coins = message.coins;
    for (let i: i32 = 0; i < coins.length; ++i) {
      writer.uint32(26);
      writer.fork();
      Coin.encode(coins[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MsgBeginUnlocking {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgBeginUnlocking();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.owner = reader.string();
          break;

        case 2:
          message.iD = reader.uint64();
          break;

        case 3:
          message.coins.push(Coin.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  owner: string;
  iD: u64;
  coins: Array<Coin>;

  constructor(owner: string = "", iD: u64 = 0, coins: Array<Coin> = []) {
    this.owner = owner;
    this.iD = iD;
    this.coins = coins;
  }
}

export function encodeMsgBeginUnlocking(
  message: MsgBeginUnlocking
): Uint8Array {
  return Protobuf.encode(message, MsgBeginUnlocking.encode);
}

export function decodeMsgBeginUnlocking(buffer: Uint8Array): MsgBeginUnlocking {
  return Protobuf.decode<MsgBeginUnlocking>(buffer, MsgBeginUnlocking.decode);
}
