// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { PeriodLock } from "./PeriodLock";

export class MsgBeginUnlockingAllResponse {
  static encode(message: MsgBeginUnlockingAllResponse, writer: Writer): void {
    const unlocks = message.unlocks;
    for (let i: i32 = 0; i < unlocks.length; ++i) {
      writer.uint32(10);
      writer.fork();
      PeriodLock.encode(unlocks[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MsgBeginUnlockingAllResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgBeginUnlockingAllResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.unlocks.push(PeriodLock.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  unlocks: Array<PeriodLock>;

  constructor(unlocks: Array<PeriodLock> = []) {
    this.unlocks = unlocks;
  }
}

export function encodeMsgBeginUnlockingAllResponse(
  message: MsgBeginUnlockingAllResponse
): Uint8Array {
  return Protobuf.encode(message, MsgBeginUnlockingAllResponse.encode);
}

export function decodeMsgBeginUnlockingAllResponse(
  buffer: Uint8Array
): MsgBeginUnlockingAllResponse {
  return Protobuf.decode<MsgBeginUnlockingAllResponse>(
    buffer,
    MsgBeginUnlockingAllResponse.decode
  );
}
