// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Duration } from "../../google/protobuf/Duration";
import { Timestamp } from "../../google/protobuf/Timestamp";
import { Coin } from "../../cosmos/base/v1beta1/Coin";

export class PeriodLock {
  static encode(message: PeriodLock, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.iD);

    writer.uint32(18);
    writer.string(message.owner);

    const duration = message.duration;
    if (duration !== null) {
      writer.uint32(26);
      writer.fork();
      Duration.encode(duration, writer);
      writer.ldelim();
    }

    const endTime = message.endTime;
    if (endTime !== null) {
      writer.uint32(34);
      writer.fork();
      Timestamp.encode(endTime, writer);
      writer.ldelim();
    }

    const coins = message.coins;
    for (let i: i32 = 0; i < coins.length; ++i) {
      writer.uint32(42);
      writer.fork();
      Coin.encode(coins[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): PeriodLock {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PeriodLock();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.iD = reader.uint64();
          break;

        case 2:
          message.owner = reader.string();
          break;

        case 3:
          message.duration = Duration.decode(reader, reader.uint32());
          break;

        case 4:
          message.endTime = Timestamp.decode(reader, reader.uint32());
          break;

        case 5:
          message.coins.push(Coin.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  iD: u64;
  owner: string;
  duration: Duration | null;
  endTime: Timestamp | null;
  coins: Array<Coin>;

  constructor(
    iD: u64 = 0,
    owner: string = "",
    duration: Duration | null = null,
    endTime: Timestamp | null = null,
    coins: Array<Coin> = []
  ) {
    this.iD = iD;
    this.owner = owner;
    this.duration = duration;
    this.endTime = endTime;
    this.coins = coins;
  }
}

export function encodePeriodLock(message: PeriodLock): Uint8Array {
  return Protobuf.encode(message, PeriodLock.encode);
}

export function decodePeriodLock(buffer: Uint8Array): PeriodLock {
  return Protobuf.decode<PeriodLock>(buffer, PeriodLock.decode);
}
