// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Timestamp } from "../../google/protobuf/Timestamp";
import { Duration } from "../../google/protobuf/Duration";

export class SyntheticLock {
  static encode(message: SyntheticLock, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.underlyingLockId);

    writer.uint32(18);
    writer.string(message.synthDenom);

    const endTime = message.endTime;
    if (endTime !== null) {
      writer.uint32(26);
      writer.fork();
      Timestamp.encode(endTime, writer);
      writer.ldelim();
    }

    const duration = message.duration;
    if (duration !== null) {
      writer.uint32(34);
      writer.fork();
      Duration.encode(duration, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): SyntheticLock {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SyntheticLock();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.underlyingLockId = reader.uint64();
          break;

        case 2:
          message.synthDenom = reader.string();
          break;

        case 3:
          message.endTime = Timestamp.decode(reader, reader.uint32());
          break;

        case 4:
          message.duration = Duration.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  underlyingLockId: u64;
  synthDenom: string;
  endTime: Timestamp | null;
  duration: Duration | null;

  constructor(
    underlyingLockId: u64 = 0,
    synthDenom: string = "",
    endTime: Timestamp | null = null,
    duration: Duration | null = null
  ) {
    this.underlyingLockId = underlyingLockId;
    this.synthDenom = synthDenom;
    this.endTime = endTime;
    this.duration = duration;
  }
}

export function encodeSyntheticLock(message: SyntheticLock): Uint8Array {
  return Protobuf.encode(message, SyntheticLock.encode);
}

export function decodeSyntheticLock(buffer: Uint8Array): SyntheticLock {
  return Protobuf.decode<SyntheticLock>(buffer, SyntheticLock.decode);
}
