// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgConnectionOpenTryResponse {
  static encode(message: MsgConnectionOpenTryResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgConnectionOpenTryResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgConnectionOpenTryResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgConnectionOpenTryResponse(
  message: MsgConnectionOpenTryResponse
): Uint8Array {
  return Protobuf.encode(message, MsgConnectionOpenTryResponse.encode);
}

export function decodeMsgConnectionOpenTryResponse(
  buffer: Uint8Array
): MsgConnectionOpenTryResponse {
  return Protobuf.decode<MsgConnectionOpenTryResponse>(
    buffer,
    MsgConnectionOpenTryResponse.decode
  );
}
