// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgChannelOpenConfirmResponse {
  static encode(message: MsgChannelOpenConfirmResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgChannelOpenConfirmResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgChannelOpenConfirmResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgChannelOpenConfirmResponse(
  message: MsgChannelOpenConfirmResponse
): Uint8Array {
  return Protobuf.encode(message, MsgChannelOpenConfirmResponse.encode);
}

export function decodeMsgChannelOpenConfirmResponse(
  buffer: Uint8Array
): MsgChannelOpenConfirmResponse {
  return Protobuf.decode<MsgChannelOpenConfirmResponse>(
    buffer,
    MsgChannelOpenConfirmResponse.decode
  );
}
