// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Height } from "../../client/v1/Height";

export class MsgChannelOpenAck {
  static encode(message: MsgChannelOpenAck, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.portId);

    writer.uint32(18);
    writer.string(message.channelId);

    writer.uint32(26);
    writer.string(message.counterpartyChannelId);

    writer.uint32(34);
    writer.string(message.counterpartyVersion);

    writer.uint32(42);
    writer.bytes(message.proofTry);

    const proofHeight = message.proofHeight;
    if (proofHeight !== null) {
      writer.uint32(50);
      writer.fork();
      Height.encode(proofHeight, writer);
      writer.ldelim();
    }

    writer.uint32(58);
    writer.string(message.signer);
  }

  static decode(reader: Reader, length: i32): MsgChannelOpenAck {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgChannelOpenAck();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.portId = reader.string();
          break;

        case 2:
          message.channelId = reader.string();
          break;

        case 3:
          message.counterpartyChannelId = reader.string();
          break;

        case 4:
          message.counterpartyVersion = reader.string();
          break;

        case 5:
          message.proofTry = reader.bytes();
          break;

        case 6:
          message.proofHeight = Height.decode(reader, reader.uint32());
          break;

        case 7:
          message.signer = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  portId: string;
  channelId: string;
  counterpartyChannelId: string;
  counterpartyVersion: string;
  proofTry: Uint8Array;
  proofHeight: Height | null;
  signer: string;

  constructor(
    portId: string = "",
    channelId: string = "",
    counterpartyChannelId: string = "",
    counterpartyVersion: string = "",
    proofTry: Uint8Array = new Uint8Array(0),
    proofHeight: Height | null = null,
    signer: string = ""
  ) {
    this.portId = portId;
    this.channelId = channelId;
    this.counterpartyChannelId = counterpartyChannelId;
    this.counterpartyVersion = counterpartyVersion;
    this.proofTry = proofTry;
    this.proofHeight = proofHeight;
    this.signer = signer;
  }
}

export function encodeMsgChannelOpenAck(
  message: MsgChannelOpenAck
): Uint8Array {
  return Protobuf.encode(message, MsgChannelOpenAck.encode);
}

export function decodeMsgChannelOpenAck(buffer: Uint8Array): MsgChannelOpenAck {
  return Protobuf.decode<MsgChannelOpenAck>(buffer, MsgChannelOpenAck.decode);
}
