// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Height } from "../../client/v1/Height";

export class MsgChannelOpenConfirm {
  static encode(message: MsgChannelOpenConfirm, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.portId);

    writer.uint32(18);
    writer.string(message.channelId);

    writer.uint32(26);
    writer.bytes(message.proofAck);

    const proofHeight = message.proofHeight;
    if (proofHeight !== null) {
      writer.uint32(34);
      writer.fork();
      Height.encode(proofHeight, writer);
      writer.ldelim();
    }

    writer.uint32(42);
    writer.string(message.signer);
  }

  static decode(reader: Reader, length: i32): MsgChannelOpenConfirm {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgChannelOpenConfirm();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.portId = reader.string();
          break;

        case 2:
          message.channelId = reader.string();
          break;

        case 3:
          message.proofAck = reader.bytes();
          break;

        case 4:
          message.proofHeight = Height.decode(reader, reader.uint32());
          break;

        case 5:
          message.signer = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  portId: string;
  channelId: string;
  proofAck: Uint8Array;
  proofHeight: Height | null;
  signer: string;

  constructor(
    portId: string = "",
    channelId: string = "",
    proofAck: Uint8Array = new Uint8Array(0),
    proofHeight: Height | null = null,
    signer: string = ""
  ) {
    this.portId = portId;
    this.channelId = channelId;
    this.proofAck = proofAck;
    this.proofHeight = proofHeight;
    this.signer = signer;
  }
}

export function encodeMsgChannelOpenConfirm(
  message: MsgChannelOpenConfirm
): Uint8Array {
  return Protobuf.encode(message, MsgChannelOpenConfirm.encode);
}

export function decodeMsgChannelOpenConfirm(
  buffer: Uint8Array
): MsgChannelOpenConfirm {
  return Protobuf.decode<MsgChannelOpenConfirm>(
    buffer,
    MsgChannelOpenConfirm.decode
  );
}
