// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Channel } from "./Channel";
import { Height } from "../../client/v1/Height";

export class MsgChannelOpenTry {
  static encode(message: MsgChannelOpenTry, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.portId);

    writer.uint32(18);
    writer.string(message.previousChannelId);

    const channel = message.channel;
    if (channel !== null) {
      writer.uint32(26);
      writer.fork();
      Channel.encode(channel, writer);
      writer.ldelim();
    }

    writer.uint32(34);
    writer.string(message.counterpartyVersion);

    writer.uint32(42);
    writer.bytes(message.proofInit);

    const proofHeight = message.proofHeight;
    if (proofHeight !== null) {
      writer.uint32(50);
      writer.fork();
      Height.encode(proofHeight, writer);
      writer.ldelim();
    }

    writer.uint32(58);
    writer.string(message.signer);
  }

  static decode(reader: Reader, length: i32): MsgChannelOpenTry {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgChannelOpenTry();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.portId = reader.string();
          break;

        case 2:
          message.previousChannelId = reader.string();
          break;

        case 3:
          message.channel = Channel.decode(reader, reader.uint32());
          break;

        case 4:
          message.counterpartyVersion = reader.string();
          break;

        case 5:
          message.proofInit = reader.bytes();
          break;

        case 6:
          message.proofHeight = Height.decode(reader, reader.uint32());
          break;

        case 7:
          message.signer = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  portId: string;
  previousChannelId: string;
  channel: Channel | null;
  counterpartyVersion: string;
  proofInit: Uint8Array;
  proofHeight: Height | null;
  signer: string;

  constructor(
    portId: string = "",
    previousChannelId: string = "",
    channel: Channel | null = null,
    counterpartyVersion: string = "",
    proofInit: Uint8Array = new Uint8Array(0),
    proofHeight: Height | null = null,
    signer: string = ""
  ) {
    this.portId = portId;
    this.previousChannelId = previousChannelId;
    this.channel = channel;
    this.counterpartyVersion = counterpartyVersion;
    this.proofInit = proofInit;
    this.proofHeight = proofHeight;
    this.signer = signer;
  }
}

export function encodeMsgChannelOpenTry(
  message: MsgChannelOpenTry
): Uint8Array {
  return Protobuf.encode(message, MsgChannelOpenTry.encode);
}

export function decodeMsgChannelOpenTry(buffer: Uint8Array): MsgChannelOpenTry {
  return Protobuf.decode<MsgChannelOpenTry>(buffer, MsgChannelOpenTry.decode);
}
