// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgRecvPacketResponse {
  static encode(message: MsgRecvPacketResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgRecvPacketResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgRecvPacketResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgRecvPacketResponse(
  message: MsgRecvPacketResponse
): Uint8Array {
  return Protobuf.encode(message, MsgRecvPacketResponse.encode);
}

export function decodeMsgRecvPacketResponse(
  buffer: Uint8Array
): MsgRecvPacketResponse {
  return Protobuf.decode<MsgRecvPacketResponse>(
    buffer,
    MsgRecvPacketResponse.decode
  );
}
