// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Packet } from "./Packet";
import { Height } from "../../client/v1/Height";

export class MsgRecvPacket {
  static encode(message: MsgRecvPacket, writer: Writer): void {
    const packet = message.packet;
    if (packet !== null) {
      writer.uint32(10);
      writer.fork();
      Packet.encode(packet, writer);
      writer.ldelim();
    }

    writer.uint32(18);
    writer.bytes(message.proofCommitment);

    const proofHeight = message.proofHeight;
    if (proofHeight !== null) {
      writer.uint32(26);
      writer.fork();
      Height.encode(proofHeight, writer);
      writer.ldelim();
    }

    writer.uint32(34);
    writer.string(message.signer);
  }

  static decode(reader: Reader, length: i32): MsgRecvPacket {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgRecvPacket();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.packet = Packet.decode(reader, reader.uint32());
          break;

        case 2:
          message.proofCommitment = reader.bytes();
          break;

        case 3:
          message.proofHeight = Height.decode(reader, reader.uint32());
          break;

        case 4:
          message.signer = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  packet: Packet | null;
  proofCommitment: Uint8Array;
  proofHeight: Height | null;
  signer: string;

  constructor(
    packet: Packet | null = null,
    proofCommitment: Uint8Array = new Uint8Array(0),
    proofHeight: Height | null = null,
    signer: string = ""
  ) {
    this.packet = packet;
    this.proofCommitment = proofCommitment;
    this.proofHeight = proofHeight;
    this.signer = signer;
  }
}

export function encodeMsgRecvPacket(message: MsgRecvPacket): Uint8Array {
  return Protobuf.encode(message, MsgRecvPacket.encode);
}

export function decodeMsgRecvPacket(buffer: Uint8Array): MsgRecvPacket {
  return Protobuf.decode<MsgRecvPacket>(buffer, MsgRecvPacket.decode);
}
