// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgUnjailResponse {
  static encode(message: MsgUnjailResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgUnjailResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgUnjailResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgUnjailResponse(
  message: MsgUnjailResponse
): Uint8Array {
  return Protobuf.encode(message, MsgUnjailResponse.encode);
}

export function decodeMsgUnjailResponse(buffer: Uint8Array): MsgUnjailResponse {
  return Protobuf.decode<MsgUnjailResponse>(buffer, MsgUnjailResponse.decode);
}
