// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class Data {
  static encode(message: Data, writer: Writer): void {
    const txs = message.txs;
    if (txs.length !== 0) {
      for (let i: i32 = 0; i < txs.length; ++i) {
        writer.uint32(10);
        writer.bytes(txs[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): Data {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Data();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.txs.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  txs: Array<Uint8Array>;

  constructor(txs: Array<Uint8Array> = []) {
    this.txs = txs;
  }
}

export function encodeData(message: Data): Uint8Array {
  return Protobuf.encode(message, Data.encode);
}

export function decodeData(buffer: Uint8Array): Data {
  return Protobuf.decode<Data>(buffer, Data.decode);
}
