// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Proof } from "../crypto/Proof";

export class TxProof {
  static encode(message: TxProof, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.rootHash);

    writer.uint32(18);
    writer.bytes(message.data);

    const proof = message.proof;
    if (proof !== null) {
      writer.uint32(26);
      writer.fork();
      Proof.encode(proof, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): TxProof {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TxProof();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.rootHash = reader.bytes();
          break;

        case 2:
          message.data = reader.bytes();
          break;

        case 3:
          message.proof = Proof.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  rootHash: Uint8Array;
  data: Uint8Array;
  proof: Proof | null;

  constructor(
    rootHash: Uint8Array = new Uint8Array(0),
    data: Uint8Array = new Uint8Array(0),
    proof: Proof | null = null
  ) {
    this.rootHash = rootHash;
    this.data = data;
    this.proof = proof;
  }
}

export function encodeTxProof(message: TxProof): Uint8Array {
  return Protobuf.encode(message, TxProof.encode);
}

export function decodeTxProof(buffer: Uint8Array): TxProof {
  return Protobuf.decode<TxProof>(buffer, TxProof.decode);
}
