// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Validator } from "./Validator";

export class ValidatorSet {
  static encode(message: ValidatorSet, writer: Writer): void {
    const validators = message.validators;
    for (let i: i32 = 0; i < validators.length; ++i) {
      writer.uint32(10);
      writer.fork();
      Validator.encode(validators[i], writer);
      writer.ldelim();
    }

    const proposer = message.proposer;
    if (proposer !== null) {
      writer.uint32(18);
      writer.fork();
      Validator.encode(proposer, writer);
      writer.ldelim();
    }

    writer.uint32(24);
    writer.int64(message.totalVotingPower);
  }

  static decode(reader: Reader, length: i32): ValidatorSet {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ValidatorSet();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.validators.push(Validator.decode(reader, reader.uint32()));
          break;

        case 2:
          message.proposer = Validator.decode(reader, reader.uint32());
          break;

        case 3:
          message.totalVotingPower = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  validators: Array<Validator>;
  proposer: Validator | null;
  totalVotingPower: i64;

  constructor(
    validators: Array<Validator> = [],
    proposer: Validator | null = null,
    totalVotingPower: i64 = 0
  ) {
    this.validators = validators;
    this.proposer = proposer;
    this.totalVotingPower = totalVotingPower;
  }
}

export function encodeValidatorSet(message: ValidatorSet): Uint8Array {
  return Protobuf.encode(message, ValidatorSet.encode);
}

export function decodeValidatorSet(buffer: Uint8Array): ValidatorSet {
  return Protobuf.decode<ValidatorSet>(buffer, ValidatorSet.decode);
}
