// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Any } from "../../../../google/protobuf/Any";

export class MsgSubmitMisbehaviour {
  static encode(message: MsgSubmitMisbehaviour, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.clientId);

    const misbehaviour = message.misbehaviour;
    if (misbehaviour !== null) {
      writer.uint32(18);
      writer.fork();
      Any.encode(misbehaviour, writer);
      writer.ldelim();
    }

    writer.uint32(26);
    writer.string(message.signer);
  }

  static decode(reader: Reader, length: i32): MsgSubmitMisbehaviour {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgSubmitMisbehaviour();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.clientId = reader.string();
          break;

        case 2:
          message.misbehaviour = Any.decode(reader, reader.uint32());
          break;

        case 3:
          message.signer = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  clientId: string;
  misbehaviour: Any | null;
  signer: string;

  constructor(
    clientId: string = "",
    misbehaviour: Any | null = null,
    signer: string = ""
  ) {
    this.clientId = clientId;
    this.misbehaviour = misbehaviour;
    this.signer = signer;
  }
}

export function encodeMsgSubmitMisbehaviour(
  message: MsgSubmitMisbehaviour
): Uint8Array {
  return Protobuf.encode(message, MsgSubmitMisbehaviour.encode);
}

export function decodeMsgSubmitMisbehaviour(
  buffer: Uint8Array
): MsgSubmitMisbehaviour {
  return Protobuf.decode<MsgSubmitMisbehaviour>(
    buffer,
    MsgSubmitMisbehaviour.decode
  );
}
