// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Any } from "../../../../google/protobuf/Any";

export class MsgUpdateClient {
  static encode(message: MsgUpdateClient, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.clientId);

    const header = message.header;
    if (header !== null) {
      writer.uint32(18);
      writer.fork();
      Any.encode(header, writer);
      writer.ldelim();
    }

    writer.uint32(26);
    writer.string(message.signer);
  }

  static decode(reader: Reader, length: i32): MsgUpdateClient {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgUpdateClient();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.clientId = reader.string();
          break;

        case 2:
          message.header = Any.decode(reader, reader.uint32());
          break;

        case 3:
          message.signer = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  clientId: string;
  header: Any | null;
  signer: string;

  constructor(
    clientId: string = "",
    header: Any | null = null,
    signer: string = ""
  ) {
    this.clientId = clientId;
    this.header = header;
    this.signer = signer;
  }
}

export function encodeMsgUpdateClient(message: MsgUpdateClient): Uint8Array {
  return Protobuf.encode(message, MsgUpdateClient.encode);
}

export function decodeMsgUpdateClient(buffer: Uint8Array): MsgUpdateClient {
  return Protobuf.decode<MsgUpdateClient>(buffer, MsgUpdateClient.decode);
}
