// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class Params {
  static encode(message: Params, writer: Writer): void {
    const allowedClients = message.allowedClients;
    if (allowedClients.length !== 0) {
      for (let i: i32 = 0; i < allowedClients.length; ++i) {
        writer.uint32(10);
        writer.string(allowedClients[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): Params {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Params();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.allowedClients.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  allowedClients: Array<string>;

  constructor(allowedClients: Array<string> = []) {
    this.allowedClients = allowedClients;
  }
}

export function encodeParams(message: Params): Uint8Array {
  return Protobuf.encode(message, Params.encode);
}

export function decodeParams(buffer: Uint8Array): Params {
  return Protobuf.decode<Params>(buffer, Params.decode);
}
