// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgGrantAllowanceResponse {
  static encode(message: MsgGrantAllowanceResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgGrantAllowanceResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgGrantAllowanceResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgGrantAllowanceResponse(
  message: MsgGrantAllowanceResponse
): Uint8Array {
  return Protobuf.encode(message, MsgGrantAllowanceResponse.encode);
}

export function decodeMsgGrantAllowanceResponse(
  buffer: Uint8Array
): MsgGrantAllowanceResponse {
  return Protobuf.decode<MsgGrantAllowanceResponse>(
    buffer,
    MsgGrantAllowanceResponse.decode
  );
}
