// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgVoteResponse {
  static encode(message: MsgVoteResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgVoteResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgVoteResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgVoteResponse(message: MsgVoteResponse): Uint8Array {
  return Protobuf.encode(message, MsgVoteResponse.encode);
}

export function decodeMsgVoteResponse(buffer: Uint8Array): MsgVoteResponse {
  return Protobuf.decode<MsgVoteResponse>(buffer, MsgVoteResponse.decode);
}
