// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Duration } from "../../../google/protobuf/Duration";

@unmanaged
export class VotingParams {
  static encode(message: VotingParams, writer: Writer): void {
    const votingPeriod = message.votingPeriod;
    if (votingPeriod !== null) {
      writer.uint32(10);
      writer.fork();
      Duration.encode(votingPeriod, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): VotingParams {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new VotingParams();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.votingPeriod = Duration.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  votingPeriod: Duration | null;

  constructor(votingPeriod: Duration | null = null) {
    this.votingPeriod = votingPeriod;
  }
}

export function encodeVotingParams(message: VotingParams): Uint8Array {
  return Protobuf.encode(message, VotingParams.encode);
}

export function decodeVotingParams(buffer: Uint8Array): VotingParams {
  return Protobuf.decode<VotingParams>(buffer, VotingParams.decode);
}
