// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { QueryCondition } from "../lockup/QueryCondition";
import { Coin } from "../../cosmos/base/v1beta1/Coin";
import { Timestamp } from "../../google/protobuf/Timestamp";

export class Gauge {
  static encode(message: Gauge, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.id);

    writer.uint32(16);
    writer.bool(message.isPerpetual);

    const distributeTo = message.distributeTo;
    if (distributeTo !== null) {
      writer.uint32(26);
      writer.fork();
      QueryCondition.encode(distributeTo, writer);
      writer.ldelim();
    }

    const coins = message.coins;
    for (let i: i32 = 0; i < coins.length; ++i) {
      writer.uint32(34);
      writer.fork();
      Coin.encode(coins[i], writer);
      writer.ldelim();
    }

    const startTime = message.startTime;
    if (startTime !== null) {
      writer.uint32(42);
      writer.fork();
      Timestamp.encode(startTime, writer);
      writer.ldelim();
    }

    writer.uint32(48);
    writer.uint64(message.numEpochsPaidOver);

    writer.uint32(56);
    writer.uint64(message.filledEpochs);

    const distributedCoins = message.distributedCoins;
    for (let i: i32 = 0; i < distributedCoins.length; ++i) {
      writer.uint32(66);
      writer.fork();
      Coin.encode(distributedCoins[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Gauge {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Gauge();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.uint64();
          break;

        case 2:
          message.isPerpetual = reader.bool();
          break;

        case 3:
          message.distributeTo = QueryCondition.decode(reader, reader.uint32());
          break;

        case 4:
          message.coins.push(Coin.decode(reader, reader.uint32()));
          break;

        case 5:
          message.startTime = Timestamp.decode(reader, reader.uint32());
          break;

        case 6:
          message.numEpochsPaidOver = reader.uint64();
          break;

        case 7:
          message.filledEpochs = reader.uint64();
          break;

        case 8:
          message.distributedCoins.push(Coin.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: u64;
  isPerpetual: bool;
  distributeTo: QueryCondition | null;
  coins: Array<Coin>;
  startTime: Timestamp | null;
  numEpochsPaidOver: u64;
  filledEpochs: u64;
  distributedCoins: Array<Coin>;

  constructor(
    id: u64 = 0,
    isPerpetual: bool = false,
    distributeTo: QueryCondition | null = null,
    coins: Array<Coin> = [],
    startTime: Timestamp | null = null,
    numEpochsPaidOver: u64 = 0,
    filledEpochs: u64 = 0,
    distributedCoins: Array<Coin> = []
  ) {
    this.id = id;
    this.isPerpetual = isPerpetual;
    this.distributeTo = distributeTo;
    this.coins = coins;
    this.startTime = startTime;
    this.numEpochsPaidOver = numEpochsPaidOver;
    this.filledEpochs = filledEpochs;
    this.distributedCoins = distributedCoins;
  }
}

export function encodeGauge(message: Gauge): Uint8Array {
  return Protobuf.encode(message, Gauge.encode);
}

export function decodeGauge(buffer: Uint8Array): Gauge {
  return Protobuf.decode<Gauge>(buffer, Gauge.decode);
}
