// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgCreateGaugeResponse {
  static encode(message: MsgCreateGaugeResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgCreateGaugeResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgCreateGaugeResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgCreateGaugeResponse(
  message: MsgCreateGaugeResponse
): Uint8Array {
  return Protobuf.encode(message, MsgCreateGaugeResponse.encode);
}

export function decodeMsgCreateGaugeResponse(
  buffer: Uint8Array
): MsgCreateGaugeResponse {
  return Protobuf.decode<MsgCreateGaugeResponse>(
    buffer,
    MsgCreateGaugeResponse.decode
  );
}
