// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { QueryCondition } from "../lockup/QueryCondition";
import { Coin } from "../../cosmos/base/v1beta1/Coin";
import { Timestamp } from "../../google/protobuf/Timestamp";

export class MsgCreateGauge {
  static encode(message: MsgCreateGauge, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.isPerpetual);

    writer.uint32(18);
    writer.string(message.owner);

    const distributeTo = message.distributeTo;
    if (distributeTo !== null) {
      writer.uint32(26);
      writer.fork();
      QueryCondition.encode(distributeTo, writer);
      writer.ldelim();
    }

    const coins = message.coins;
    for (let i: i32 = 0; i < coins.length; ++i) {
      writer.uint32(34);
      writer.fork();
      Coin.encode(coins[i], writer);
      writer.ldelim();
    }

    const startTime = message.startTime;
    if (startTime !== null) {
      writer.uint32(42);
      writer.fork();
      Timestamp.encode(startTime, writer);
      writer.ldelim();
    }

    writer.uint32(48);
    writer.uint64(message.numEpochsPaidOver);
  }

  static decode(reader: Reader, length: i32): MsgCreateGauge {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgCreateGauge();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.isPerpetual = reader.bool();
          break;

        case 2:
          message.owner = reader.string();
          break;

        case 3:
          message.distributeTo = QueryCondition.decode(reader, reader.uint32());
          break;

        case 4:
          message.coins.push(Coin.decode(reader, reader.uint32()));
          break;

        case 5:
          message.startTime = Timestamp.decode(reader, reader.uint32());
          break;

        case 6:
          message.numEpochsPaidOver = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  isPerpetual: bool;
  owner: string;
  distributeTo: QueryCondition | null;
  coins: Array<Coin>;
  startTime: Timestamp | null;
  numEpochsPaidOver: u64;

  constructor(
    isPerpetual: bool = false,
    owner: string = "",
    distributeTo: QueryCondition | null = null,
    coins: Array<Coin> = [],
    startTime: Timestamp | null = null,
    numEpochsPaidOver: u64 = 0
  ) {
    this.isPerpetual = isPerpetual;
    this.owner = owner;
    this.distributeTo = distributeTo;
    this.coins = coins;
    this.startTime = startTime;
    this.numEpochsPaidOver = numEpochsPaidOver;
  }
}

export function encodeMsgCreateGauge(message: MsgCreateGauge): Uint8Array {
  return Protobuf.encode(message, MsgCreateGauge.encode);
}

export function decodeMsgCreateGauge(buffer: Uint8Array): MsgCreateGauge {
  return Protobuf.decode<MsgCreateGauge>(buffer, MsgCreateGauge.decode);
}
