// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { DVPair } from "./DVPair";

export class DVPairs {
  static encode(message: DVPairs, writer: Writer): void {
    const pairs = message.pairs;
    for (let i: i32 = 0; i < pairs.length; ++i) {
      writer.uint32(10);
      writer.fork();
      DVPair.encode(pairs[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): DVPairs {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DVPairs();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.pairs.push(DVPair.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  pairs: Array<DVPair>;

  constructor(pairs: Array<DVPair> = []) {
    this.pairs = pairs;
  }
}

export function encodeDVPairs(message: DVPairs): Uint8Array {
  return Protobuf.encode(message, DVPairs.encode);
}

export function decodeDVPairs(buffer: Uint8Array): DVPairs {
  return Protobuf.decode<DVPairs>(buffer, DVPairs.decode);
}
