// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class DVVTriplet {
  static encode(message: DVVTriplet, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.delegatorAddress);

    writer.uint32(18);
    writer.string(message.validatorSrcAddress);

    writer.uint32(26);
    writer.string(message.validatorDstAddress);
  }

  static decode(reader: Reader, length: i32): DVVTriplet {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DVVTriplet();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.delegatorAddress = reader.string();
          break;

        case 2:
          message.validatorSrcAddress = reader.string();
          break;

        case 3:
          message.validatorDstAddress = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  delegatorAddress: string;
  validatorSrcAddress: string;
  validatorDstAddress: string;

  constructor(
    delegatorAddress: string = "",
    validatorSrcAddress: string = "",
    validatorDstAddress: string = ""
  ) {
    this.delegatorAddress = delegatorAddress;
    this.validatorSrcAddress = validatorSrcAddress;
    this.validatorDstAddress = validatorDstAddress;
  }
}

export function encodeDVVTriplet(message: DVVTriplet): Uint8Array {
  return Protobuf.encode(message, DVVTriplet.encode);
}

export function decodeDVVTriplet(buffer: Uint8Array): DVVTriplet {
  return Protobuf.decode<DVVTriplet>(buffer, DVVTriplet.decode);
}
