// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { DVVTriplet } from "./DVVTriplet";

export class DVVTriplets {
  static encode(message: DVVTriplets, writer: Writer): void {
    const triplets = message.triplets;
    for (let i: i32 = 0; i < triplets.length; ++i) {
      writer.uint32(10);
      writer.fork();
      DVVTriplet.encode(triplets[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): DVVTriplets {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DVVTriplets();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.triplets.push(DVVTriplet.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  triplets: Array<DVVTriplet>;

  constructor(triplets: Array<DVVTriplet> = []) {
    this.triplets = triplets;
  }
}

export function encodeDVVTriplets(message: DVVTriplets): Uint8Array {
  return Protobuf.encode(message, DVVTriplets.encode);
}

export function decodeDVVTriplets(buffer: Uint8Array): DVVTriplets {
  return Protobuf.decode<DVVTriplets>(buffer, DVVTriplets.decode);
}
