// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Coin } from "../../base/v1beta1/Coin";

export class MsgBeginRedelegate {
  static encode(message: MsgBeginRedelegate, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.delegatorAddress);

    writer.uint32(18);
    writer.string(message.validatorSrcAddress);

    writer.uint32(26);
    writer.string(message.validatorDstAddress);

    const amount = message.amount;
    if (amount !== null) {
      writer.uint32(34);
      writer.fork();
      Coin.encode(amount, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MsgBeginRedelegate {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgBeginRedelegate();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.delegatorAddress = reader.string();
          break;

        case 2:
          message.validatorSrcAddress = reader.string();
          break;

        case 3:
          message.validatorDstAddress = reader.string();
          break;

        case 4:
          message.amount = Coin.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  delegatorAddress: string;
  validatorSrcAddress: string;
  validatorDstAddress: string;
  amount: Coin | null;

  constructor(
    delegatorAddress: string = "",
    validatorSrcAddress: string = "",
    validatorDstAddress: string = "",
    amount: Coin | null = null
  ) {
    this.delegatorAddress = delegatorAddress;
    this.validatorSrcAddress = validatorSrcAddress;
    this.validatorDstAddress = validatorDstAddress;
    this.amount = amount;
  }
}

export function encodeMsgBeginRedelegate(
  message: MsgBeginRedelegate
): Uint8Array {
  return Protobuf.encode(message, MsgBeginRedelegate.encode);
}

export function decodeMsgBeginRedelegate(
  buffer: Uint8Array
): MsgBeginRedelegate {
  return Protobuf.decode<MsgBeginRedelegate>(buffer, MsgBeginRedelegate.decode);
}
