// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Coin } from "../../base/v1beta1/Coin";

export class MsgDelegate {
  static encode(message: MsgDelegate, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.delegatorAddress);

    writer.uint32(18);
    writer.string(message.validatorAddress);

    const amount = message.amount;
    if (amount !== null) {
      writer.uint32(26);
      writer.fork();
      Coin.encode(amount, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MsgDelegate {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgDelegate();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.delegatorAddress = reader.string();
          break;

        case 2:
          message.validatorAddress = reader.string();
          break;

        case 3:
          message.amount = Coin.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  delegatorAddress: string;
  validatorAddress: string;
  amount: Coin | null;

  constructor(
    delegatorAddress: string = "",
    validatorAddress: string = "",
    amount: Coin | null = null
  ) {
    this.delegatorAddress = delegatorAddress;
    this.validatorAddress = validatorAddress;
    this.amount = amount;
  }
}

export function encodeMsgDelegate(message: MsgDelegate): Uint8Array {
  return Protobuf.encode(message, MsgDelegate.encode);
}

export function decodeMsgDelegate(buffer: Uint8Array): MsgDelegate {
  return Protobuf.decode<MsgDelegate>(buffer, MsgDelegate.decode);
}
