// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Timestamp } from "../../../google/protobuf/Timestamp";

@unmanaged
export class MsgUndelegateResponse {
  static encode(message: MsgUndelegateResponse, writer: Writer): void {
    const completionTime = message.completionTime;
    if (completionTime !== null) {
      writer.uint32(10);
      writer.fork();
      Timestamp.encode(completionTime, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MsgUndelegateResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgUndelegateResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.completionTime = Timestamp.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  completionTime: Timestamp | null;

  constructor(completionTime: Timestamp | null = null) {
    this.completionTime = completionTime;
  }
}

export function encodeMsgUndelegateResponse(
  message: MsgUndelegateResponse
): Uint8Array {
  return Protobuf.encode(message, MsgUndelegateResponse.encode);
}

export function decodeMsgUndelegateResponse(
  buffer: Uint8Array
): MsgUndelegateResponse {
  return Protobuf.decode<MsgUndelegateResponse>(
    buffer,
    MsgUndelegateResponse.decode
  );
}
