// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { RedelegationEntry } from "./RedelegationEntry";

export class Redelegation {
  static encode(message: Redelegation, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.delegatorAddress);

    writer.uint32(18);
    writer.string(message.validatorSrcAddress);

    writer.uint32(26);
    writer.string(message.validatorDstAddress);

    const entries = message.entries;
    for (let i: i32 = 0; i < entries.length; ++i) {
      writer.uint32(34);
      writer.fork();
      RedelegationEntry.encode(entries[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Redelegation {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Redelegation();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.delegatorAddress = reader.string();
          break;

        case 2:
          message.validatorSrcAddress = reader.string();
          break;

        case 3:
          message.validatorDstAddress = reader.string();
          break;

        case 4:
          message.entries.push(
            RedelegationEntry.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  delegatorAddress: string;
  validatorSrcAddress: string;
  validatorDstAddress: string;
  entries: Array<RedelegationEntry>;

  constructor(
    delegatorAddress: string = "",
    validatorSrcAddress: string = "",
    validatorDstAddress: string = "",
    entries: Array<RedelegationEntry> = []
  ) {
    this.delegatorAddress = delegatorAddress;
    this.validatorSrcAddress = validatorSrcAddress;
    this.validatorDstAddress = validatorDstAddress;
    this.entries = entries;
  }
}

export function encodeRedelegation(message: Redelegation): Uint8Array {
  return Protobuf.encode(message, Redelegation.encode);
}

export function decodeRedelegation(buffer: Uint8Array): Redelegation {
  return Protobuf.decode<Redelegation>(buffer, Redelegation.decode);
}
