// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class DecProto {
  static encode(message: DecProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.dec);
  }

  static decode(reader: Reader, length: i32): DecProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DecProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.dec = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  dec: string;

  constructor(dec: string = "") {
    this.dec = dec;
  }
}

export function encodeDecProto(message: DecProto): Uint8Array {
  return Protobuf.encode(message, DecProto.encode);
}

export function decodeDecProto(buffer: Uint8Array): DecProto {
  return Protobuf.decode<DecProto>(buffer, DecProto.decode);
}
