// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class IntProto {
  static encode(message: IntProto, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.int);
  }

  static decode(reader: Reader, length: i32): IntProto {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new IntProto();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.int = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  int: string;

  constructor(int: string = "") {
    this.int = int;
  }
}

export function encodeIntProto(message: IntProto): Uint8Array {
  return Protobuf.encode(message, IntProto.encode);
}

export function decodeIntProto(buffer: Uint8Array): IntProto {
  return Protobuf.decode<IntProto>(buffer, IntProto.decode);
}
