// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class MsgExecResponse {
  static encode(message: MsgExecResponse, writer: Writer): void {
    const results = message.results;
    if (results.length !== 0) {
      for (let i: i32 = 0; i < results.length; ++i) {
        writer.uint32(10);
        writer.bytes(results[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): MsgExecResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgExecResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.results.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  results: Array<Uint8Array>;

  constructor(results: Array<Uint8Array> = []) {
    this.results = results;
  }
}

export function encodeMsgExecResponse(message: MsgExecResponse): Uint8Array {
  return Protobuf.encode(message, MsgExecResponse.encode);
}

export function decodeMsgExecResponse(buffer: Uint8Array): MsgExecResponse {
  return Protobuf.decode<MsgExecResponse>(buffer, MsgExecResponse.decode);
}
