// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgRevokeResponse {
  static encode(message: MsgRevokeResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgRevokeResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgRevokeResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgRevokeResponse(
  message: MsgRevokeResponse
): Uint8Array {
  return Protobuf.encode(message, MsgRevokeResponse.encode);
}

export function decodeMsgRevokeResponse(buffer: Uint8Array): MsgRevokeResponse {
  return Protobuf.decode<MsgRevokeResponse>(buffer, MsgRevokeResponse.decode);
}
