// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgMultiSendResponse {
  static encode(message: MsgMultiSendResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgMultiSendResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgMultiSendResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgMultiSendResponse(
  message: MsgMultiSendResponse
): Uint8Array {
  return Protobuf.encode(message, MsgMultiSendResponse.encode);
}

export function decodeMsgMultiSendResponse(
  buffer: Uint8Array
): MsgMultiSendResponse {
  return Protobuf.decode<MsgMultiSendResponse>(
    buffer,
    MsgMultiSendResponse.decode
  );
}
