// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { ExistenceProof } from "./ExistenceProof";
import { NonExistenceProof } from "./NonExistenceProof";
import { BatchProof } from "./BatchProof";
import { CompressedBatchProof } from "./CompressedBatchProof";

export class CommitmentProof {
  static encode(message: CommitmentProof, writer: Writer): void {
    const exist = message.exist;
    if (exist !== null) {
      writer.uint32(10);
      writer.fork();
      ExistenceProof.encode(exist, writer);
      writer.ldelim();
    }

    const nonexist = message.nonexist;
    if (nonexist !== null) {
      writer.uint32(18);
      writer.fork();
      NonExistenceProof.encode(nonexist, writer);
      writer.ldelim();
    }

    const batch = message.batch;
    if (batch !== null) {
      writer.uint32(26);
      writer.fork();
      BatchProof.encode(batch, writer);
      writer.ldelim();
    }

    const compressed = message.compressed;
    if (compressed !== null) {
      writer.uint32(34);
      writer.fork();
      CompressedBatchProof.encode(compressed, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CommitmentProof {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CommitmentProof();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.exist = ExistenceProof.decode(reader, reader.uint32());
          break;

        case 2:
          message.nonexist = NonExistenceProof.decode(reader, reader.uint32());
          break;

        case 3:
          message.batch = BatchProof.decode(reader, reader.uint32());
          break;

        case 4:
          message.compressed = CompressedBatchProof.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  exist: ExistenceProof | null;
  nonexist: NonExistenceProof | null;
  batch: BatchProof | null;
  compressed: CompressedBatchProof | null;

  constructor(
    exist: ExistenceProof | null = null,
    nonexist: NonExistenceProof | null = null,
    batch: BatchProof | null = null,
    compressed: CompressedBatchProof | null = null
  ) {
    this.exist = exist;
    this.nonexist = nonexist;
    this.batch = batch;
    this.compressed = compressed;
  }
}

export function encodeCommitmentProof(message: CommitmentProof): Uint8Array {
  return Protobuf.encode(message, CommitmentProof.encode);
}

export function decodeCommitmentProof(buffer: Uint8Array): CommitmentProof {
  return Protobuf.decode<CommitmentProof>(buffer, CommitmentProof.decode);
}
