// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { LeafOp } from "./LeafOp";
import { InnerOp } from "./InnerOp";

export class ExistenceProof {
  static encode(message: ExistenceProof, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.key);

    writer.uint32(18);
    writer.bytes(message.value);

    const leaf = message.leaf;
    if (leaf !== null) {
      writer.uint32(26);
      writer.fork();
      LeafOp.encode(leaf, writer);
      writer.ldelim();
    }

    const path = message.path;
    for (let i: i32 = 0; i < path.length; ++i) {
      writer.uint32(34);
      writer.fork();
      InnerOp.encode(path[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ExistenceProof {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ExistenceProof();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.key = reader.bytes();
          break;

        case 2:
          message.value = reader.bytes();
          break;

        case 3:
          message.leaf = LeafOp.decode(reader, reader.uint32());
          break;

        case 4:
          message.path.push(InnerOp.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  key: Uint8Array;
  value: Uint8Array;
  leaf: LeafOp | null;
  path: Array<InnerOp>;

  constructor(
    key: Uint8Array = new Uint8Array(0),
    value: Uint8Array = new Uint8Array(0),
    leaf: LeafOp | null = null,
    path: Array<InnerOp> = []
  ) {
    this.key = key;
    this.value = value;
    this.leaf = leaf;
    this.path = path;
  }
}

export function encodeExistenceProof(message: ExistenceProof): Uint8Array {
  return Protobuf.encode(message, ExistenceProof.encode);
}

export function decodeExistenceProof(buffer: Uint8Array): ExistenceProof {
  return Protobuf.decode<ExistenceProof>(buffer, ExistenceProof.decode);
}
