// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { StringEvent } from "./StringEvent";

export class ABCIMessageLog {
  static encode(message: ABCIMessageLog, writer: Writer): void {
    writer.uint32(8);
    writer.uint32(message.msgIndex);

    writer.uint32(18);
    writer.string(message.log);

    const events = message.events;
    for (let i: i32 = 0; i < events.length; ++i) {
      writer.uint32(26);
      writer.fork();
      StringEvent.encode(events[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ABCIMessageLog {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ABCIMessageLog();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.msgIndex = reader.uint32();
          break;

        case 2:
          message.log = reader.string();
          break;

        case 3:
          message.events.push(StringEvent.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  msgIndex: u32;
  log: string;
  events: Array<StringEvent>;

  constructor(
    msgIndex: u32 = 0,
    log: string = "",
    events: Array<StringEvent> = []
  ) {
    this.msgIndex = msgIndex;
    this.log = log;
    this.events = events;
  }
}

export function encodeABCIMessageLog(message: ABCIMessageLog): Uint8Array {
  return Protobuf.encode(message, ABCIMessageLog.encode);
}

export function decodeABCIMessageLog(buffer: Uint8Array): ABCIMessageLog {
  return Protobuf.decode<ABCIMessageLog>(buffer, ABCIMessageLog.decode);
}
