// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class MsgData {
  static encode(message: MsgData, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.msgType);

    writer.uint32(18);
    writer.bytes(message.data);
  }

  static decode(reader: Reader, length: i32): MsgData {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgData();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.msgType = reader.string();
          break;

        case 2:
          message.data = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  msgType: string;
  data: Uint8Array;

  constructor(msgType: string = "", data: Uint8Array = new Uint8Array(0)) {
    this.msgType = msgType;
    this.data = data;
  }
}

export function encodeMsgData(message: MsgData): Uint8Array {
  return Protobuf.encode(message, MsgData.encode);
}

export function decodeMsgData(buffer: Uint8Array): MsgData {
  return Protobuf.decode<MsgData>(buffer, MsgData.decode);
}
