// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Coin } from "../../../cosmos/base/v1beta1/Coin";

export class MsgExitPool {
  static encode(message: MsgExitPool, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.sender);

    writer.uint32(16);
    writer.uint64(message.poolId);

    writer.uint32(26);
    writer.string(message.shareInAmount);

    const tokenOutMins = message.tokenOutMins;
    for (let i: i32 = 0; i < tokenOutMins.length; ++i) {
      writer.uint32(34);
      writer.fork();
      Coin.encode(tokenOutMins[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MsgExitPool {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgExitPool();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sender = reader.string();
          break;

        case 2:
          message.poolId = reader.uint64();
          break;

        case 3:
          message.shareInAmount = reader.string();
          break;

        case 4:
          message.tokenOutMins.push(Coin.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  sender: string;
  poolId: u64;
  shareInAmount: string;
  tokenOutMins: Array<Coin>;

  constructor(
    sender: string = "",
    poolId: u64 = 0,
    shareInAmount: string = "",
    tokenOutMins: Array<Coin> = []
  ) {
    this.sender = sender;
    this.poolId = poolId;
    this.shareInAmount = shareInAmount;
    this.tokenOutMins = tokenOutMins;
  }
}

export function encodeMsgExitPool(message: MsgExitPool): Uint8Array {
  return Protobuf.encode(message, MsgExitPool.encode);
}

export function decodeMsgExitPool(buffer: Uint8Array): MsgExitPool {
  return Protobuf.decode<MsgExitPool>(buffer, MsgExitPool.decode);
}
