// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgExitSwapShareAmountInResponse {
  static encode(
    message: MsgExitSwapShareAmountInResponse,
    writer: Writer
  ): void {}

  static decode(reader: Reader, length: i32): MsgExitSwapShareAmountInResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgExitSwapShareAmountInResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgExitSwapShareAmountInResponse(
  message: MsgExitSwapShareAmountInResponse
): Uint8Array {
  return Protobuf.encode(message, MsgExitSwapShareAmountInResponse.encode);
}

export function decodeMsgExitSwapShareAmountInResponse(
  buffer: Uint8Array
): MsgExitSwapShareAmountInResponse {
  return Protobuf.decode<MsgExitSwapShareAmountInResponse>(
    buffer,
    MsgExitSwapShareAmountInResponse.decode
  );
}
