// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgExitPoolResponse {
  static encode(message: MsgExitPoolResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgExitPoolResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgExitPoolResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgExitPoolResponse(
  message: MsgExitPoolResponse
): Uint8Array {
  return Protobuf.encode(message, MsgExitPoolResponse.encode);
}

export function decodeMsgExitPoolResponse(
  buffer: Uint8Array
): MsgExitPoolResponse {
  return Protobuf.decode<MsgExitPoolResponse>(
    buffer,
    MsgExitPoolResponse.decode
  );
}
