// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Coin } from "../../../cosmos/base/v1beta1/Coin";

export class MsgExitSwapExternAmountOut {
  static encode(message: MsgExitSwapExternAmountOut, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.sender);

    writer.uint32(16);
    writer.uint64(message.poolId);

    const tokenOut = message.tokenOut;
    if (tokenOut !== null) {
      writer.uint32(26);
      writer.fork();
      Coin.encode(tokenOut, writer);
      writer.ldelim();
    }

    writer.uint32(34);
    writer.string(message.shareInMaxAmount);
  }

  static decode(reader: Reader, length: i32): MsgExitSwapExternAmountOut {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgExitSwapExternAmountOut();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sender = reader.string();
          break;

        case 2:
          message.poolId = reader.uint64();
          break;

        case 3:
          message.tokenOut = Coin.decode(reader, reader.uint32());
          break;

        case 4:
          message.shareInMaxAmount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  sender: string;
  poolId: u64;
  tokenOut: Coin | null;
  shareInMaxAmount: string;

  constructor(
    sender: string = "",
    poolId: u64 = 0,
    tokenOut: Coin | null = null,
    shareInMaxAmount: string = ""
  ) {
    this.sender = sender;
    this.poolId = poolId;
    this.tokenOut = tokenOut;
    this.shareInMaxAmount = shareInMaxAmount;
  }
}

export function encodeMsgExitSwapExternAmountOut(
  message: MsgExitSwapExternAmountOut
): Uint8Array {
  return Protobuf.encode(message, MsgExitSwapExternAmountOut.encode);
}

export function decodeMsgExitSwapExternAmountOut(
  buffer: Uint8Array
): MsgExitSwapExternAmountOut {
  return Protobuf.decode<MsgExitSwapExternAmountOut>(
    buffer,
    MsgExitSwapExternAmountOut.decode
  );
}
