// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgExitSwapExternAmountOutResponse {
  static encode(
    message: MsgExitSwapExternAmountOutResponse,
    writer: Writer
  ): void {}

  static decode(
    reader: Reader,
    length: i32
  ): MsgExitSwapExternAmountOutResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgExitSwapExternAmountOutResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgExitSwapExternAmountOutResponse(
  message: MsgExitSwapExternAmountOutResponse
): Uint8Array {
  return Protobuf.encode(message, MsgExitSwapExternAmountOutResponse.encode);
}

export function decodeMsgExitSwapExternAmountOutResponse(
  buffer: Uint8Array
): MsgExitSwapExternAmountOutResponse {
  return Protobuf.decode<MsgExitSwapExternAmountOutResponse>(
    buffer,
    MsgExitSwapExternAmountOutResponse.decode
  );
}
