// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgSwapExactAmountInResponse {
  static encode(message: MsgSwapExactAmountInResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgSwapExactAmountInResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgSwapExactAmountInResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgSwapExactAmountInResponse(
  message: MsgSwapExactAmountInResponse
): Uint8Array {
  return Protobuf.encode(message, MsgSwapExactAmountInResponse.encode);
}

export function decodeMsgSwapExactAmountInResponse(
  buffer: Uint8Array
): MsgSwapExactAmountInResponse {
  return Protobuf.decode<MsgSwapExactAmountInResponse>(
    buffer,
    MsgSwapExactAmountInResponse.decode
  );
}
