// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class MsgSwapExactAmountOutResponse {
  static encode(message: MsgSwapExactAmountOutResponse, writer: Writer): void {}

  static decode(reader: Reader, length: i32): MsgSwapExactAmountOutResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MsgSwapExactAmountOutResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeMsgSwapExactAmountOutResponse(
  message: MsgSwapExactAmountOutResponse
): Uint8Array {
  return Protobuf.encode(message, MsgSwapExactAmountOutResponse.encode);
}

export function decodeMsgSwapExactAmountOutResponse(
  buffer: Uint8Array
): MsgSwapExactAmountOutResponse {
  return Protobuf.decode<MsgSwapExactAmountOutResponse>(
    buffer,
    MsgSwapExactAmountOutResponse.decode
  );
}
