// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class SwapAmountInRoute {
  static encode(message: SwapAmountInRoute, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.poolId);

    writer.uint32(18);
    writer.string(message.tokenOutDenom);
  }

  static decode(reader: Reader, length: i32): SwapAmountInRoute {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SwapAmountInRoute();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.poolId = reader.uint64();
          break;

        case 2:
          message.tokenOutDenom = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  poolId: u64;
  tokenOutDenom: string;

  constructor(poolId: u64 = 0, tokenOutDenom: string = "") {
    this.poolId = poolId;
    this.tokenOutDenom = tokenOutDenom;
  }
}

export function encodeSwapAmountInRoute(
  message: SwapAmountInRoute
): Uint8Array {
  return Protobuf.encode(message, SwapAmountInRoute.encode);
}

export function decodeSwapAmountInRoute(buffer: Uint8Array): SwapAmountInRoute {
  return Protobuf.decode<SwapAmountInRoute>(buffer, SwapAmountInRoute.decode);
}
